name: setup-ossutil2
description: aliyun ossutil2 setup action
author: rogerogers

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: upload
  color: purple

# Define your inputs here.

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
